---
- hosts: all
  gather_facts: true

  vars_files:
    - vars.yml

  tasks:

  - debug: msg="{{linux_upgrade_packages}}"
  - debug: msg="{{lvm_pe_size}}"

  - debug: var=hostvars[inventory_hostname]


  - debug: var="(hostvars[inventory_hostname].lb_primary == True) | ternary('MASTER','BACKUP')"

  #- debug: var="{{ (groups['loadbalancers'].index(inventory_hostname) == 0) | ternary('MASTER','BACKUP') }}"


  - debug: var=groups['databases']

  - debug: var=(hostvars[groups['databases'][0]].ansible_host)
  - debug: msg="{{ (hostvars[groups['databases'][0]].ansible_host) }}"

  - debug:
      msg: "{{ item }}"
    loop: "{{ groups['webservers'] }}"

  - debug:
      msg: "{{ item }} - {{ hostvars[item].ansible_host }}"
    loop: "{{ groups['webservers'] }}"


  - debug:
      msg: "{{ hostvars[item].ansible_host }}/32"
    loop: "{{ groups['webservers'] }}"

  - name: Print available facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts['interfaces'] }}"


  - name: Print available facts using hostvars
    ansible.builtin.debug:
      msg: "{{ hostvars[inventory_hostname]['ansible_facts']['interfaces'] }}"

  - name: Get Primary Interface
    ansible.builtin.debug:
      msg: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['interface'] }}"

  - name: Get Primary Interface from first loadbalancer host on inventory
    ansible.builtin.debug:
      msg: "{{ hostvars[groups['loadbalancers'][0]]['ansible_default_ipv4']['interface'] }}"

  - debug: msg="{{ vrrp_nic }}"